name: Tests
on:
  repository_dispatch:
    types: [tests-report]
  push:
jobs:
  unit-tests:
    name: Unit tests
    strategy:
      matrix:
        platform: [ubuntu-latest]  # , windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Run integration test
        run: cd integration-tests && cargo run --example integration-tests
      - name: Run unit tests
        run: cd market-contract && cargo test
        run: cd ../nft-contract && cargo test
        run: cd ../nft-contract-approval && cargo test
        run: cd ../nft-contract-basic && cargo test
        run: cd ../nft-contract-events && cargo test
        run: cd ../nft-contract-royalty && cargo test
        run: cd ../nft-contract-skeleton && cargo test
        run: cd ../nft-series && cargo test